### PR TITLE
optional() stackable function; changes in tests for better readability

### PR DESCRIPTION
**Pull request by d9k**

### CODE REVIEW

**Comment by Etiene** [comment]
That's a great addition! thanks for your contribution!

The indentation seems to not be matching though, could you fix that before I merge? 
thanks!

**Comment by eugene-p** [comment]
My only comment it should also evaluate `0` and an empty string same way as `nil`

**Comment by d9k** [comment]
@eugene-p, please provide examples where treating `0` and empty string as `nil` is useful behavior.

**Comment by d9k** [comment]
@eugene-p, what about `0` as `nil`?

**Comment by eugene-p** [comment]
We had that discussion in original issue. Makes more sense to treat it same
way. Either way should be clearly documented.

**Comment by d9k** [comment]
@eugene-p, I read issues https://github.com/sailorproject/valua/issues/10 and https://github.com/sailorproject/valua/issues/11 and I didn't find clear example why `0` should be treated as `nil`.

I agree about treating empty strings as `nil`, what about the `0`?

**Comment by d9k** [comment]
@eugene-p, maybe we just need to process form data with some simple external function (which converts empty strings to `nil`s) before passing this form data to `valua`...

**Pull request merged**
