### PR TITLE
add coveralls.io support

### PR DESCRIPTION
**Pull request by fperrad**
A registration is needed on https://coveralls.io/github/sailorproject

I cannot test the deployment.

### CODE REVIEW

**Comment by Etiene** [comment]
Just registered. We might need an additional file with a token. Can you open this page?
https://coveralls.io/github/sailorproject/valua

**Comment by Etiene** [comment]
I can also give you commit access to test this :)

**Comment by Etiene** [comment]
many thanks for this PR 💃

**Comment by fperrad** [comment]
Works fine. I see the badge with "coverage 93%".

**Comment by fperrad** [comment]
In order to have a more accurate coverage, line like this
```lua
	if l < min or l > max then return false,"should have "..tostring(min).."-"..tostring(max).." characters" end
```
must be splited
```lua
	if l < min or l > max then
            return false,"should have "..tostring(min).."-"..tostring(max).." characters"
        end
```

**Pull request merged**
